version: '2'

services:
  logstash:
    image: logstash:6.6.2
    container_name: elk-logstash
    volumes:
      - /etc/container/elk/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    ports:
      - "6500:6500/udp"
      - "514:5514/tcp"
      - "514:5514/udp"
    environment:
      http.host: "0.0.0.0"
      ES_JAVA_OPTS: '-Xms2048m -Xmx2048m'

  elasticsearch:
    image: elasticsearch:6.6.2
    container_name: elk-elasticsearch
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data:rw
    environment:
      cluster.name: "elasticsearch"
      network.host: 0.0.0.0
      discovery.zen.minimum_master_nodes: 1
      discovery.type: single-node
      # bootstrap.memory_lock: 'true'
      ES_JAVA_OPTS: '-Xms2048m -Xmx2048m'

  kibana:
    image: kibana:6.6.2
    container_name: elk-kibana
    environment:
      server.name: kibana
      server.host: "0"
      elasticsearch.url: http://elasticsearch:9200
    depends_on:
      - elasticsearch

  nginx:
    image: nginx:1.15.9-alpine
    container_name: elk-nginx
    volumes:
      - /etc/container/elk/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - kibana

volumes:
  elasticsearch:
    driver: local
